In [2]:
from __future__ import print_function
import numpy as np

import sys
from datetime import datetime

In [3]:
def pythonsum(n):
    a = range(n)
    b = range(n)
    c = []

    for i in range(len(a)):
        a[i] = i ** 2
        b[i] = i ** 3
        c.append(a[i] + b[i])

    return c

In [4]:
# using numpy

def numpysum(n):
    a = np.arange(n) ** 2
    b = np.arange(n) ** 3
    c = a + b

    return c

In [11]:
a = np.arange(5)
a.dtype

b = np.array([[[0,1,2,3,4], [5,6,7,8,9]],
              [[0,1,2,3,4], [5,6,7,8,9]],
              [[0,1,2,3,4], [5,6,7,8,9]]])
b.shape

(3, 2, 5)

In [14]:
c = np.arange(9)
print(c[3:7])
print(c[:7:2])
print(c[::-1])

[3 4 5 6]
[0 2 4 6]
[8 7 6 5 4 3 2 1 0]


In [20]:
d = np.arange(24).reshape(2,3,4)

d.shape
d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [22]:
e = d.ravel()

e.shape
e

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [24]:
f = d.flatten()
f

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [27]:
f.shape = (6,4)
f


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [3]:
a1 = np.array([[1,2],[3,4]])
a2 = a1.ravel()
a3 = a1.flatten()
a4 = a1.reshape(-1)

In [4]:
a1[0][0] = 99

In [6]:
print(a2)
print(a3)
print(a4)

# flatten() results in deep copy,
# whereas ravel() and reshape(-1) result in shallow copy

[99  2  3  4]
[1 2 3 4]
[99  2  3  4]


In [23]:
# stacking
k1 = np.arange(9).reshape(3,3)
print(k1)
k2 = 2*k1
print(k2)

print("\n")

# horizontal stacking
print("hstack : \n",np.hstack((k1,k2)),"\n")
# same as
print("concatenate, axis 1 : \n", np.concatenate((k1,k2), axis=1), "\n")

# vertical stacking

print("vstack : \n", np.vstack((k1,k2)), "\n")
# same as
print("concatenate, axis 0 : \n", np.concatenate((k1, k2),axis=0), "\n")


# depth stacking
print("dstack : \n", np.dstack((k1,k2)), '\n')
np.dstack((k1,k2)).shape

# column stacking
oned = np.arange(2)
twice_oned = oned * 2

print("column_stack : \n", np.column_stack((oned, twice_oned)))

# row stacking

print("row_stack : \n", np.row_stack((oned, twice_oned)), "\n")

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]


hstack : 
 [[ 0  1  2  0  2  4]
 [ 3  4  5  6  8 10]
 [ 6  7  8 12 14 16]] 

concatenate, axis 1 : 
 [[ 0  1  2  0  2  4]
 [ 3  4  5  6  8 10]
 [ 6  7  8 12 14 16]] 

vstack : 
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 0  2  4]
 [ 6  8 10]
 [12 14 16]] 

concatenate, axis 0 : 
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 0  2  4]
 [ 6  8 10]
 [12 14 16]] 

dstack : 
 [[[ 0  0]
  [ 1  2]
  [ 2  4]]

 [[ 3  6]
  [ 4  8]
  [ 5 10]]

 [[ 6 12]
  [ 7 14]
  [ 8 16]]] 

column_stack : 
 [[0 0]
 [1 2]]
row_stack : 
 [[0 1]
 [0 2]] 



In [32]:
# splitting

t1 = np.arange(9).reshape(3,3)

t2,t3,t4 = np.hsplit(t1, 3)

print(t2, '\n')
print(t3, '\n')
print(t4, '\n')

t5,t6,t7 = np.split(t1, 3, axis=1)

print(t5, '\n')
print(t6, '\n')
print(t7, '\n')

# depth-wise splitting

t1 = np.arange(27).reshape(3,3,3)

t8, t9, t10 = np.dsplit(t1, 3)

t8.shape


[[0]
 [3]
 [6]] 

[[1]
 [4]
 [7]] 

[[2]
 [5]
 [8]] 

[[0]
 [3]
 [6]] 

[[1]
 [4]
 [7]] 

[[2]
 [5]
 [8]] 



(3, 3, 1)

In [50]:
# ndarray attributes

# 1. ndim : gives the number of dimensions
h1 = np.arange(12)
print(h1.ndim)
h1 = h1.reshape(3,4)
print(h1.ndim)
h1 = h1.reshape(2,2,3)
print(h1.ndim, '\n')

# 2. size : gives the number of elements
print('size : ',h1.size)

# 3. itemsize : gives the number of bytes for each elements
print('itemsize : ', h1.itemsize)

# 4. nbytes : gives the total bytes of array, same as itemsize * size
print('nbytes : ', h1.nbytes)

# 5. T : same as ndarray.transpose()
h1 = h1.reshape(3,4)

print(h1)
print(h1.transpose())
print(h1.T)

1
2
3 

size :  12
itemsize :  4
nbytes :  48
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [55]:
# converting ndarray to python list

l1 = np.arange(9).reshape(3,3)
print(l1.tolist())

# converting datatypes

l2 = l1.astype(np.float32)
print(l2)

[[0, 1, 2], [3, 4, 5], [6, 7, 8]]
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
