In [2]:
import tensorflow as tf
import numpy as np

In [3]:
# Variables
# tf.Variables represents a tensor whose value can be manipulated.

sample_tensor = tf.constant([2,3])
print(sample_tensor[0],'\n') # 2
# sample_tensor[0] += 1 # Error

my_tensor = tf.constant([[1.0, 2.0],[3.0, 4.0]])
my_variable = tf.Variable(my_tensor)

print(my_tensor, '\n')
print(my_variable,'\n')

bool_variable = tf.Variable([False,False,False,True])
complex_variable = tf.Variable([5 + 4j, 6 + 1j])

# tf.Variables are backed by tensors. like tensors, they have dtype and shape

print("Shape : ",my_variable.shape)
print("Dtype : ",my_variable.dtype)
print("As numpy : ",my_variable.numpy())

tf.Tensor(2, shape=(), dtype=int32) 

tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32) 

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)> 

Shape :  (2, 2)
Dtype :  <dtype: 'float32'>
As numpy :  [[1. 2.]
 [3. 4.]]


In [4]:
print("A variable : ", my_variable)
print("Viewed as a tensor : ", tf.convert_to_tensor(my_variable))
print("Index of highest value : ", tf.argmax(my_variable))

print("Copying and reshaping : ", tf.reshape(my_variable, [1,4]))

A variable :  <tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>
Viewed as a tensor :  tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
Index of highest value :  tf.Tensor([1 1], shape=(2,), dtype=int64)
Copying and reshaping :  tf.Tensor([[1. 2. 3. 4.]], shape=(1, 4), dtype=float32)


In [6]:
# reassign the tensor using tf.Variable.assign. it does not allocate new tensor. instead, existing tensor's memory is reused.
a = tf.Variable([2.0, 3.0])
a.assign([1,2])

# after assigning, dtype is still float32.
print(a)
# Not allowed, because it resizes the variable.
try:
    a.assign([1.0, 2.0, 3.0])
except Exception as e:
    print(f"{type(e).__name__}: {e}")

<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([1., 2.], dtype=float32)>
ValueError: Cannot assign value to variable ' Variable:0': Shape mismatch.The variable shape (2,), and the assigned value shape (3,) are incompatible.


In [8]:
a = tf.Variable([2.0, 3.0])
b = tf.Variable(a)
a.assign([5,6])

# creating new variable based on existiong variable wil copy the variable. (shallow copy)
print(a.numpy())
print(b.numpy())

# other assigning methods
print(a.assign_add([2,3]).numpy())
print(a.assign_sub([7,9]).numpy())

[5. 6.]
[2. 3.]
[7. 9.]
[0. 0.]


In [11]:
a = tf.Variable(my_tensor, name="Mark")
b = tf.Variable(my_tensor + 1, name="Mark")

print(a==b)
step_counter = tf.Variable(1, trainable=False)

tf.Tensor(
[[False False]
 [False False]], shape=(2, 2), dtype=bool)


In [12]:
# Placing variables and tensors (GPU or CPU)

with tf.device('CPU:0'):
    a = tf.Variable([[1.0, 2.0, 3.0],[4.0, 5.0, 6.0]])
    b = tf.constant([[1.0,2.0],[3.0,4.0],[5.0,6.0]])
    c = tf.matmul(a,b)
print(c)

tf.Tensor(
[[22. 28.]
 [49. 64.]], shape=(2, 2), dtype=float32)


In [13]:
with tf.device('CPU:0'):
    a = tf.Variable([[1.0, 2.0, 3.0],[4.0, 5.0, 6.0]])
    b = tf.Variable([1.0,2.0,3.0])
with tf.device('GPU:0'):
    k = a * b

print(k)

tf.Tensor(
[[ 1.  4.  9.]
 [ 4. 10. 18.]], shape=(2, 3), dtype=float32)
