In [1]:
import tensorflow as tf
import numpy as np

In [2]:
# Every tensor is immutable. can only be created

In [27]:
# How to Create tensor. Can specify datatype
tensor = tf.constant(4, dtype=tf.float32)
print(tensor)

tf.Tensor(4.0, shape=(), dtype=float32)


In [16]:
# Rank-0 tensor (scalar)

rank_0_tensor = tf.constant(4)
print(type(rank_0_tensor))
print(rank_0_tensor.dtype)
print(rank_0_tensor.shape)
print(rank_0_tensor)

<class 'tensorflow.python.framework.ops.EagerTensor'>
<dtype: 'int32'>
()
tf.Tensor(4, shape=(), dtype=int32)


In [17]:
# Rank-1 tensor (vector)

rank_1_tensor = tf.constant([4,3,2])
print(type(rank_1_tensor))
print(rank_1_tensor.dtype)
print(rank_1_tensor.shape)
print(rank_1_tensor)

<class 'tensorflow.python.framework.ops.EagerTensor'>
<dtype: 'int32'>
(3,)
tf.Tensor([4 3 2], shape=(3,), dtype=int32)


In [18]:
# Rank-2 tensor (array)

rank_2_tensor = tf.constant([[4,3,2],[1,2,3],[5,6,7]])
print(type(rank_2_tensor))
print(rank_2_tensor.dtype)
print(rank_2_tensor.shape)
print(rank_2_tensor)

<class 'tensorflow.python.framework.ops.EagerTensor'>
<dtype: 'int32'>
(3, 3)
tf.Tensor(
[[4 3 2]
 [1 2 3]
 [5 6 7]], shape=(3, 3), dtype=int32)


In [5]:
# Rank-n tensor

# rank_n_tensor = tf.constant([[[4,3,2],[1,2,3],[5,6,7]] ... [8,7,6],[5,7,8]])
# print(rank_n_tensor)

tf.Tensor(
[[4 3 2]
 [1 2 3]
 [5 6 7]], shape=(3, 3), dtype=int32)


In [25]:
# Convert tf.tensor to np.array

# method 1. Using np.array()
nparr1 = np.array(rank_2_tensor)
print('type of nparr1 : ' + str(type(nparr1)))

# method 2. Using tensor.numpy()
nparr2 = rank_2_tensor.numpy()
print('type of nparr2 : ' + str(type(nparr2)))

type of nparr1 : <class 'numpy.ndarray'>
type of nparr2 : <class 'numpy.ndarray'>
