In [2]:
import tensorflow as tf
import numpy as np

In [3]:
# Every tensor is immutable. can only be created

In [4]:
# How to Create tensor. Can specify datatype
tensor = tf.constant(4, dtype=tf.float32)
print(tensor)

tf.Tensor(4.0, shape=(), dtype=float32)


In [5]:
# Rank-0 tensor (scalar)

rank_0_tensor = tf.constant(4)
print(type(rank_0_tensor))
print(rank_0_tensor.dtype)
print(rank_0_tensor.shape)
print(rank_0_tensor)

<class 'tensorflow.python.framework.ops.EagerTensor'>
<dtype: 'int32'>
()
tf.Tensor(4, shape=(), dtype=int32)


In [6]:
# Rank-1 tensor (vector)

rank_1_tensor = tf.constant([4,3,2])
print(type(rank_1_tensor))
print(rank_1_tensor.dtype)
print(rank_1_tensor.shape)
print(rank_1_tensor)

<class 'tensorflow.python.framework.ops.EagerTensor'>
<dtype: 'int32'>
(3,)
tf.Tensor([4 3 2], shape=(3,), dtype=int32)


In [7]:
# Rank-2 tensor (array)

rank_2_tensor = tf.constant([[4,3,2],[1,2,3],[5,6,7]])
print(type(rank_2_tensor))
print(rank_2_tensor.dtype)
print(rank_2_tensor.shape)
print(rank_2_tensor)

<class 'tensorflow.python.framework.ops.EagerTensor'>
<dtype: 'int32'>
(3, 3)
tf.Tensor(
[[4 3 2]
 [1 2 3]
 [5 6 7]], shape=(3, 3), dtype=int32)


In [8]:
# Rank-n tensor

# rank_n_tensor = tf.constant([[[4,3,2],[1,2,3],[5,6,7]] ... [8,7,6],[5,7,8]])
# print(rank_n_tensor)

In [9]:
# Convert tf.tensor to np.array

# method 1. Using np.array()
nparr1 = np.array(rank_2_tensor)
print('type of nparr1 : ' + str(type(nparr1)))

# method 2. Using tensor.numpy()
nparr2 = rank_2_tensor.numpy()
print('type of nparr2 : ' + str(type(nparr2)))

type of nparr1 : <class 'numpy.ndarray'>
type of nparr2 : <class 'numpy.ndarray'>


In [10]:
# Basic operations
a = tf.constant([[1,2],[3,4]])
b = tf.constant([[1,1],[1,1]]) # = tf.ones([2,2])

print(tf.add(a,b))      #element-wise operation
print(tf.multiply(a,b)) #element-wise operation
print(tf.matmul(a,b))   #matrix multiplication
print('\n')
# same as..
print(a + b)
print(a * b)
print(a @ b)

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32)


tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32)


In [11]:
# Other operations
c = tf.constant([[1.0, 3.5],[7.3, -5.0]])

# Find the largest value
print(tf.reduce_max(c))
# Find the index of the largest value
print(tf.argmax(c))
# Compute the softmax
print(tf.nn.softmax(c))
# set negative value to zero
print(tf.nn.relu(c))
print(tf.nn.sigmoid(c))

tf.Tensor(7.3, shape=(), dtype=float32)
tf.Tensor([1 0], shape=(2,), dtype=int64)
tf.Tensor(
[[7.5858176e-02 9.2414182e-01]
 [9.9999547e-01 4.5517231e-06]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1.  3.5]
 [7.3 0. ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0.73105854 0.97068775]
 [0.9993249  0.00669285]], shape=(2, 2), dtype=float32)


In [15]:
# tf.reduce API

t1 = tf.random.uniform((3,3), maxval=10, dtype=tf.int32)
t2 = tf.constant([True, True, False])
print(t1.numpy())

print(tf.reduce_sum(t1).numpy()) # sum of all elements
print(tf.reduce_prod(t1).numpy()) # product of all elements
print(tf.reduce_max(t1).numpy()) # maximum of all elements
print(tf.reduce_min(t1).numpy()) # minimum of all elements
print(tf.reduce_mean(t1).numpy()) # mean value of all elements
print(tf.reduce_all(t2).numpy()) # AND operation
print(tf.reduce_any(t2).numpy()) # OR operation

# tf.reduce operation with specified axis (channel-wise operation)
print(tf.reduce_sum(t1, axis=0).numpy())

[[4 5 4]
 [7 3 2]
 [1 8 4]]
38
107520
8
1
4
False
True
[12 16 10]


In [12]:
# Tensor shapes
rank_4_tensor = tf.zeros([3,2,4,5])
print("Type of elements :", rank_4_tensor.dtype)
print("Number of axes :", rank_4_tensor.ndim)
print("Number of tensor :", rank_4_tensor.shape)
print("Elements along axis 0 of tensor :", rank_4_tensor.shape[0])
print("Elements along last axis of tensor :", rank_4_tensor.shape[-1])
print("Total number of elements (3*2*4*5) :", tf.size(rank_4_tensor).numpy())

# shape : [3, 2, 4, 5]
# The length (number of elements) of each of the axes of a tensor

# Rank : 4
# Number of tensor axes

# Axis / Dimension
# A particular dimension of a tensor

# Size : 120
# The total number of items in the tensor, the product shape vector

# Typical axis order of a rank-4-tensor
# | Batch | Width | Height | Features

Type of elements : <dtype: 'float32'>
Number of axes : 4
Number of tensor : (3, 2, 4, 5)
Elements along axis 0 of tensor : 3
Elements along last axis of tensor : 5
Total number of elements (3*2*4*5) : 120


In [13]:
# Indexing
# Same as python indexing rule

# Single-axis indexing
rank_1_tensor = tf.constant([0, 1, 1, 2, 3, 5, 8, 13, 21, 34])
print(rank_1_tensor.numpy())
print("First : ", rank_1_tensor[0].numpy())
print("Second : ", rank_1_tensor[1].numpy())
print("Last : ", rank_1_tensor[-1].numpy())

print("Everything : ", rank_1_tensor[:].numpy())
print("Before 4 : ", rank_1_tensor[:4].numpy())
print("From 4 to the end : ", rank_1_tensor[4:].numpy())
print("From 2, before 7 : ", rank_1_tensor[2:7].numpy())
print("Every other item : ", rank_1_tensor[::2].numpy())
print("Reversed : ", rank_1_tensor[::-1].numpy())

# Multi-axis indexing
print(rank_2_tensor.numpy())

print("Single value : ", rank_2_tensor[1,1].numpy())
print("Second row : ", rank_2_tensor[1,:].numpy())
print("Second column : ", rank_2_tensor[:,1].numpy())
print("Last row : ", rank_2_tensor[-1,:].numpy())
print("First item in Last column : ", rank_2_tensor[0,-1].numpy())
print("Skip the first row : ", rank_2_tensor[1:,:].numpy())

[ 0  1  1  2  3  5  8 13 21 34]
First :  0
Second :  1
Last :  34
Everything :  [ 0  1  1  2  3  5  8 13 21 34]
Before 4 :  [0 1 1 2]
From 4 to the end :  [ 3  5  8 13 21 34]
From 2, before 7 :  [1 2 3 5 8]
Every other item :  [ 0  1  3  8 21]
Reversed :  [34 21 13  8  5  3  2  1  1  0]
[[4 3 2]
 [1 2 3]
 [5 6 7]]
Single value :  2
Second row :  [1 2 3]
Second column :  [3 2 6]
Last row :  [5 6 7]
First item in Last column :  2
Skip the first row :  [[1 2 3]
 [5 6 7]]


In [24]:
# Manipulating Shapes
x = tf.constant([[1],[2],[3]])
print(x.shape)
print(type(x.shape))

# Convert "Tensorshape" object to python List
print(x.shape.as_list())
print(type(x.shape.as_list()))

reshaped = tf.reshape(x, [1, 3])

print(x.shape)
print(reshaped.shape)

rank_3_tensor = tf.constant([[[0,1,2,3,4],[5,6,7,8,9]],[[10,11,12,13,14],[15,16,17,18,19]],[[20,21,22,23,24],[25,26,27,28,29]]])
print(rank_3_tensor)

print(tf.reshape(rank_3_tensor, [-1])) # -1 means : Whatever fits
print(tf.reshape(rank_3_tensor,[6,5]))
print(tf.reshape(rank_3_tensor,[3,-1]))

# Bad examples for reshaping tensors
print(tf.reshape(rank_3_tensor, [2,3,5])) # Cannot reorder axes with reshape. use tf.transpose instead.

(3, 1)
<class 'tensorflow.python.framework.tensor_shape.TensorShape'>
[3, 1]
<class 'list'>
(3, 1)
(1, 3)
tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)
tf.Tensor(
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29], shape=(30,), dtype=int32)
tf.Tensor(
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]], shape=(6, 5), dtype=int32)
tf.Tensor(
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]], shape=(3, 10), dtype=int32)
tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]], shape=(2, 3, 5), dtype=int32)


In [25]:
# when not specified, python integers will be tf.int32, and python floating points to tf.float32

the_f64_tensor = tf.constant([2.2,3.3,4.4], dtype=tf.float64)
the_f16_tensor = tf.cast(the_f64_tensor, dtype=tf.float16)
the_u8_tensor = tf.cast(the_f16_tensor, dtype=tf.uint8)
print(the_u8_tensor)

tf.Tensor([2 3 4], shape=(3,), dtype=uint8)


In [35]:
# Broadcasting
# Similar feature as numpy

x = tf.constant([1,2,3])
y = tf.constant(2)
z = tf.constant([2,2,2])

# All operations are equal
print(tf.multiply(x,2))
print(x * y)
print(x * z)

x = tf.reshape(x, [3,1])
y = tf.range(1,5)
print(x)
print(y)

print(tf.multiply(x,y))
# Same as multiplying
# x : [1,1,1,1],
#     [2,2,2,2],
#     [3,3,3,3],
#     [4,4,4,4]

# y : [1,2,3,4],
#     [1,2,3,4],
#     [1,2,3,4],
#     [1,2,3,4]

# materialize broadcasted tensor
print(tf.broadcast_to(tf.constant([1,2,3]),[2,3]))

tf.Tensor([2 4 6], shape=(3,), dtype=int32)
tf.Tensor([2 4 6], shape=(3,), dtype=int32)
tf.Tensor([2 4 6], shape=(3,), dtype=int32)
tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32)
tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
tf.Tensor(
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]], shape=(3, 4), dtype=int32)
tf.Tensor(
[[1 2 3]
 [1 2 3]], shape=(2, 3), dtype=int32)


In [39]:
# Ragged tensors
# tensor with variable numbers of elements along some axis is called ragged tensor

ragged_list = [[0,1,2,3],[4,5],[6,7,8],[9]]

try:
    tensor = tf.constant(ragged_list)
except Exception as e:
    print(f"{type(e).__name__}: {e}")

ragged_tensor = tf.ragged.constant(ragged_list)
print(ragged_tensor)
print(ragged_tensor.shape)

ValueError: Can't convert non-rectangular Python sequence to Tensor.
<tf.RaggedTensor [[0, 1, 2, 3], [4, 5], [6, 7, 8], [9]]>
(4, None)


In [44]:
# String tensors

scalar_string_tensor = tf.constant(['Gray wolf'])
print(scalar_string_tensor)

tensor_of_strings = tf.constant(['Gray wolf','Quick brown fox','Laxy dog'])
print(tensor_of_strings)

print(tf.strings.split(scalar_string_tensor, sep= " "))
print(tf.strings.split(tensor_of_strings, sep= " "))

tf.Tensor([b'Gray wolf'], shape=(1,), dtype=string)
tf.Tensor([b'Gray wolf' b'Quick brown fox' b'Laxy dog'], shape=(3,), dtype=string)
<tf.RaggedTensor [[b'Gray', b'wolf']]>
<tf.RaggedTensor [[b'Gray', b'wolf'], [b'Quick', b'brown', b'fox'], [b'Laxy', b'dog']]>


In [46]:
# Sparse tensors
# tensor with sparse data with embedding spaces

sparse_tensor = tf.sparse.SparseTensor(indices=[[0,0],[1,2]],
                                       values=[1,2],
                                       dense_shape=[3,4])

print(sparse_tensor)
# convert sparse tensor to dense tensor

print(tf.sparse.to_dense(sparse_tensor))

SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))
tf.Tensor(
[[1 0 0 0]
 [0 0 2 0]
 [0 0 0 0]], shape=(3, 4), dtype=int32)
